---
title: "IGI mrgsolve Shiny"
author: "Justin Penzenstadler"
date: "September 15, 2016"
output: html_document
---

```{r}
library(shiny)
library(tidyr)
library(ggplot2)
library(openxlsx)
library(dplyr)
library(lubridate)
library(stringr)
```



```{r}
ui<- fluidPage(
    tabsetPanel(
      tabPanel('BUILD',
        titlePanel("TO Auto-builder"),
        sidebarLayout(
          sidebarPanel(
            fileInput('file', label = h3("File input"), multiple = T),
            uiOutput('selectDrugs'),
            textInput('group_name', 'Group Name - No Spaces', 'Add Group Name Here'),
            actionButton('pushgrp',"PUSH TO ADD TO GROUP"),
            actionButton('pushsingle',"PUSH TO ADD ALL AS SINGLE"),
            uiOutput('selectRange'),
            dateRangeInput('dateRange0',
            label = 'Select Total Timeframe',
            start = Sys.Date() - 365, end = Sys.Date() + 365, separator = 'to'),
            dateRangeInput('dateRange1',
            label = 'Select Comparator Timeframe 1',
            start = Sys.Date() - 2, end = Sys.Date() + 2, separator = 'to'),
            dateRangeInput('dateRange2',
            label = 'Select Comparator Timeframe 2',
            start = Sys.Date() - 2, end = Sys.Date() + 2, separator = 'to')),
          mainPanel(tableOutput("table2"),
                    plotOutput('summaryTable'),
          width = 6
         ))
       ),
    tabPanel('PLOTS', 
        titlePanel("LOESS Spending Curves"),
        p('This will output spending trends for a single selected drug over the selected Total Timeframe'),
        uiOutput('selectdrugPlot'),
        plotOutput('drugPlot'))
  )
)  
```


```{r}
server<-function(input, output) {
  
##############################################TAB ONE #######################################################  

########################MAIN DATASET FROM UPLOAD############################    
  Dataset <- reactive({
    #### returns blank data.frame() if there is no data yet. prevents errors.
    if (is.null(input$file)) {
      return(data.frame())
    }
    
    Dataset <- data.frame()
    
    for(n in 1:nrow(input$file)){
      Dataset <- Dataset %>% bind_rows(read.xlsx(input$file[[n, 'datapath']]))
    }
    
    Dataset <- Dataset %>%
              mutate(Week = gsub('Week ', '', Week)) %>%          ##make Week numeric
              separate(Week, c('Week', 'Year'), ', ') %>%         ##separate Week/Year into different columns 
              mutate(Week = str_pad(Week, 2, pad = '0')) %>%       ##Pad Week so that it is always 2 digits
              mutate(Date = as.numeric(paste(1,paste(Year, Week, sep = ''), sep = ''))) %>%  ##add a day (aka u in lubridate) for each date.  it is a bug.
              mutate(Date = parse_date_time(as.character(Date), orders = "uYW")) %>% 
              mutate(Month = month(Date)) %>% 
              mutate(Group = NA) %>%
              as.data.frame()
    return(Dataset)
  })  
  
  #############################REACTIVE UI ELEMENTS###########################
  
  output$selectDrugs <- renderUI({
        input$pushgrp 
        drug_list = unique(Dataset()$Generic.Name)
        selectizeInput('selected_drugs_list', 'Choose or Search for Drugs', choices = sort(drug_list), multiple = TRUE)
    })
    
  output$selectRange <- renderUI({
        time_range = list(min = min(Dataset()$Date, na.rm = T), 
               max = max(Dataset()$Date, na.rm = T)) 
        string = paste('The Data Uploaded Contains Dates', as.character(time_range$min), as.character(time_range$max))
        p(string)
    })
  
  ###########################BUILDING OF GROUPINGS OF DRUGS######################
  
  values <- reactiveValues(df_data = NULL)   #INITIALIZE GROUP. VALUES IS THE GROUP DF

  observeEvent(input$pushgrp, {              #IF MAKE GROUP BUTTON IS PUSHED, ADD CURRENT SELECTED DRUGS AS grouped item to values 
    temp = list(input$selected_drugs_list)
    names(temp) <- eval(input$group_name)
    values$df_data <- c(values$df_data,temp)

  })
  
  observeEvent(input$pushsingle, {
    temp = as.list(input$selected_drugs_list)
    names(temp) <- c(input$selected_drugs_list)
    values$df_data <- c(values$df_data,temp)

  })

output$table10 <- renderDataTable({as.data.frame(values$df_data)})   #kill this maybe for final development version? 


#################this makes the main output with totals and monthly per group/drug#####################################
  output$table2 <- renderTable({

        df <- Dataset()
              ##below assigns each group/single in a named list as a item in df$group.
        for(n in names(values$df_data)){
               group_name = n
               group_drugs = values$df_data[[n]]
               df$Group = ifelse(df$Generic.Name %in% group_drugs, n, df$Group)
        }
        

            daterange0 <- as.list(unlist(strsplit(as.character(input$dateRange0), 'to')))
            names(daterange0) <- c('min', 'max')
            
            daterange1 <- as.list(unlist(strsplit(as.character(input$dateRange1), 'to')))
            names(daterange1) <- c('min', 'max')
            
            daterange2 <- as.list(unlist(strsplit(as.character(input$dateRange2), 'to')))
            names(daterange2) <- c('min', 'max')
            
            
          working_df <- df %>% 
            filter(ymd(Date) >= ymd(daterange0$min) & ymd(Date) < ymd(daterange0$max)) %>%
                filter(!is.na(Group))
          
          
            totals_by_month <- working_df %>% 
              group_by(Group, Month) %>% 
              summarize(sum = sum(Total.Spend, na.rm = T))
        
            totals_by_Timeframe1 <- working_df %>% 
              filter(ymd(Date) >= ymd(daterange1$min) & ymd(Date) < ymd(daterange1$max))%>%
              group_by(Group) %>% summarize(Timeframe1 = sum(Total.Spend, na.rm = T))
            
            totals_by_Timeframe2 <- working_df %>% 
              filter(ymd(Date) >= ymd(daterange2$min) & ymd(Date) < ymd(daterange2$max))%>%
              group_by(Group) %>% summarize(Timeframe2 = sum(Total.Spend, na.rm = T))
            
             table <- full_join(totals_by_month, totals_by_Timeframe1, by = "Group") %>% 
              full_join(totals_by_Timeframe2, by ='Group') %>% 
               mutate(Month = month.abb[Month]) %>%
               spread(Month, sum) %>%
               mutate(Percent_Change = (Timeframe2 - Timeframe1) * 100 /Timeframe2)
           
            table
            

  })
  
  
  
  output$summaryTable <- renderPlot({
    
    daterange0 <- as.list(unlist(strsplit(as.character(input$dateRange0), 'to')))
    names(daterange0) <- c('min', 'max')
    
    df <- Dataset()
    df <- df %>% 
      filter(ymd(Date) >= ymd(daterange0$min) & ymd(Date) < ymd(daterange0$max)) %>%
      group_by(Generic.Name) %>% 
      summarize(Total_spend = sum(Total.Spend)) %>% 
      top_n(20, Total_spend)
    
    ggplot(df) + geom_bar(aes(x = reorder(Generic.Name, Total_spend), y = Total_spend), stat = 'identity') + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    
    })
  

######################################################TAB TWO #############################################################
  output$selectdrugPlot <- renderUI({
        drug_list = unique(Dataset()$Generic.Name)
        checkboxGroupInput('plotDrug', 'Choose Drug to Plot', sort(drug_list))
    })
  
  output$drugPlot <- renderPlot({
    
    daterange0 <- as.list(unlist(strsplit(as.character(input$dateRange0), 'to')))
    names(daterange0) <- c('min', 'max')
    
    df <- Dataset()
    df <- df %>% 
      filter(ymd(Date) >= ymd(daterange0$min) & ymd(Date) < ymd(daterange0$max)) %>%
      filter(Generic.Name == input$plotDrug)
    
    try(ggplot(df) + geom_smooth(aes(x = Date, y = Total.Spend)))
    ggplot(df) + geom_point(aes(x = Date, y = Total.Spend, color = Generic.Name))
    })
  
  
  
  
  
  
  
}

```

```{r}
shinyApp(ui = ui, server = server)
```